name: Deploy on Pull Request

on:
  push:
    branches: [ main ]
    
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Deploy code to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@16.170.235.219 'bash -s' < . ./script.sh
