name: Run Script on EC2

on:
  push:
    branches: [deploy]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Script on EC2
        run: |
          cd code/backend
          npm install
          npm run build
          cp .env ./dist
          chmod +x run.sh
          ./run.sh
          pm2 save
